version: "3.9"

services:
  logspout:
    image: gliderlabs/logspout
    hostname: "{{.Service.Name}}"
    networks:
      - host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SYSLOG_STRUCTURED_DATA: "e8e16e85-8a60-4e6a-9870-0af7a8235cbb@41058"
      tag: "Logspout"
    command: syslog+tcp://logs-01.loggly.com:514
    #deploy:
    #  mode: global
    #  resources:
    #    limits:
    #      cpus: '0.20'
    #      memory: 256M
    #    reservations:
    #      cpus: '0.10'
    #      memory: 128M