version: '3.9'
services:
  raven1:
    image: ${CONTAINER_IMAGE}
    container_name: raven1
    networks:
      - camilonet
    ports:
      - 8081:8080
      - 38881:38888
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_Logs_Mode=Information
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_PublicServerUrl=http://raven1:8080
      - RAVEN_PublicServerUrl_Tcp=tcp://raven1:38888
      - RAVEN_License_Eula_Accepted=true

  raven2:
    image: ${CONTAINER_IMAGE}
    container_name: raven2
    networks:
      - camilonet
    ports:
      - 8082:8080
      - 38882:38888
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_Logs_Mode=Information
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_PublicServerUrl=http://raven2:8080
      - RAVEN_PublicServerUrl_Tcp=tcp://raven2:38888
      - RAVEN_License_Eula_Accepted=true
    depends_on:
      - raven1

networks:
  camilonet:

volumes:
  data:
